### ISSUE TITLE
Upgrade `vite-imagetools`

### ISSUE THREAD

**Issue by benmccann** [HassanZahirnia/laravel-imagetools-issue#1]
Can you update `vite-imagetools` to the latest and let me know if this repo is still broken?

**Comment by HassanZahirnia** [comment]
Yeah the issue still exist, even after updating `vite-imagetools` to `4.0.16`

![image](https://user-images.githubusercontent.com/15275787/214153464-af883f4b-7c35-42e9-a0ee-84d97bf42c3a.png)

**Comment by benmccann** [comment]
thanks!

**Comment by benmccann** [comment]
I just released 4.0.17 which adds a leading `/` which seems to be the issue folks were reporting. Can you try again and let me know if it works now?

**Comment by HassanZahirnia** [comment]
No it doesn't work :(

**Comment by benmccann** [comment]
darn
